import Link from "next/link";
import type { ReactNode } from "react";
import { Archive, FolderKanban, Search } from "lucide-react";
import { dashboardData } from "@/features/notes/queries";
import { QuickCapture } from "@/features/notes/components/quick-capture";
import { NotesList } from "@/features/notes/components/notes-list";

export default async function PanelPage({ searchParams }: { searchParams: Promise<{ q?: string; archived?: string }> }) { const params = await searchParams; const archived = params.archived === "1"; const data = await dashboardData(params.q, archived); return <div className="mx-auto max-w-6xl space-y-7 pb-12"><header className="rounded-[2rem] border border-border bg-card p-6 shadow-[0_18px_50px_rgba(40,34,20,.06)] sm:p-9"><p className="font-mono text-xs uppercase tracking-[.18em] text-primary">Your thinking space</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">A calm place for<br/>your moving thoughts.</h1><p className="mt-3 max-w-lg text-sm leading-6 text-muted-foreground">Capture the useful details while you work. Organize later, when you have room to think.</p></div><QuickCapture projects={data.projects} defaultExpirationDays={data.settings.defaultExpirationDays}/></div><div className="mt-8 grid max-w-md grid-cols-2 gap-3"><Metric icon={<FolderKanban className="size-4"/>} label="Projects" value={String(data.projects.length)}/><Metric icon={<Archive className="size-4"/>} label={archived ? "Archived" : "On your desk"} value={String(data.notes.length)}/></div></header><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex rounded-xl bg-[#ebe8df] p-1 text-sm"><Link href="/panel" className={`rounded-lg px-3 py-1.5 ${!archived ? "bg-card text-foreground shadow-sm" : "text-muted-foreground"}`}>Active notes</Link><Link href="/panel?archived=1" className={`rounded-lg px-3 py-1.5 ${archived ? "bg-card text-foreground shadow-sm" : "text-muted-foreground"}`}>Archive</Link></div><form className="flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-1 shadow-sm"><Search className="size-4 text-muted-foreground"/><input name="q" defaultValue={params.q} className="w-full bg-transparent py-2 text-sm outline-none placeholder:text-muted-foreground" placeholder="Find a note"/><input type="hidden" name="archived" value={archived ? "1" : ""}/></form></section><NotesList notes={data.notes} archived={archived}/></div>; }
function Metric({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="rounded-2xl bg-[#f2f0ea] p-3.5"><div className="flex items-center gap-2 text-xs text-muted-foreground">{icon}{label}</div><p className="mt-2 text-xl font-semibold">{value}</p></div>; }
