import Link from "next/link";
import { Plus, Search } from "lucide-react";
import { dashboardData } from "@/features/notes/queries";
import { QuickCapture } from "@/features/notes/components/quick-capture";
import { NotesList } from "@/features/notes/components/notes-list";

export default async function PanelPage({ searchParams }: { searchParams: Promise<{ q?: string; archived?: string }> }) {
  const params = await searchParams; const archived = params.archived === "1"; const data = await dashboardData(params.q, archived);
  const lanes = [{ id: "inbox", name: "Inbox", notes: data.notes.filter((note) => !note.project) }, ...data.projects.map((project) => ({ id: project.id, name: project.name, notes: data.notes.filter((note) => note.project?.id === project.id) }))];
  return <div className="flex h-full min-w-0 flex-col"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-primary">Workspace</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">My board</h1></div><div className="flex items-center gap-3"><form className="hidden items-center gap-2 rounded-md border border-border bg-card px-3 py-1.5 sm:flex"><Search className="size-4 text-muted-foreground"/><input name="q" defaultValue={params.q} className="w-44 bg-transparent text-sm outline-none placeholder:text-muted-foreground" placeholder="Search cards"/><input type="hidden" name="archived" value={archived ? "1" : ""}/></form><QuickCapture projects={data.projects} defaultExpirationDays={data.settings.defaultExpirationDays}/></div></header><nav className="mb-5 flex items-center gap-1 border-b border-border text-sm"><Link href="/panel" className={`border-b-2 px-3 py-2.5 ${!archived ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}>Board</Link><Link href="/panel?archived=1" className={`border-b-2 px-3 py-2.5 ${archived ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}>Archive</Link><Link href="/panel/projects" className="border-b-2 border-transparent px-3 py-2.5 text-muted-foreground hover:text-foreground">Projects</Link></nav><div className="min-h-0 flex-1 overflow-x-auto pb-5"><div className="flex min-h-full min-w-max items-start gap-3">{lanes.map((lane) => <section key={lane.id} className="w-72 shrink-0"><header className="mb-3 flex items-center justify-between px-1"><h2 className="truncate text-sm font-semibold">{lane.name}</h2><span className="font-mono text-xs text-muted-foreground">{lane.notes.length}</span></header><div className="min-h-36 rounded-lg bg-[#202020] p-2"><NotesList notes={lane.notes} archived={archived} compact/></div><button className="mt-2 flex w-full items-center gap-1.5 rounded-md px-2 py-1.5 text-xs text-muted-foreground transition hover:bg-muted hover:text-foreground"><Plus className="size-3.5"/>Add card</button></section>)}<Link href="/panel/projects" className="mt-9 grid size-10 shrink-0 place-items-center rounded-md border border-dashed border-border text-muted-foreground hover:border-primary hover:text-primary" aria-label="Create project"><Plus className="size-4"/></Link></div></div></div>;
}
