import Link from "next/link";
import type { ReactNode } from "react";
import { Archive, FolderKanban, Search } from "lucide-react";
import { dashboardData } from "@/features/notes/queries";
import { QuickCapture } from "@/features/notes/components/quick-capture";
import { NotesList } from "@/features/notes/components/notes-list";

export default async function PanelPage({ searchParams }: { searchParams: Promise<{ q?: string; archived?: string }> }) { const params = await searchParams; const archived = params.archived === "1"; const data = await dashboardData(params.q, archived); return <div className="mx-auto max-w-6xl space-y-8 pb-12"><header className="rounded-3xl border border-[#35453a] bg-[radial-gradient(circle_at_75%_0%,#284636_0%,transparent_38%),#171e1b] p-6 sm:p-9"><p className="font-mono text-xs uppercase tracking-[.18em] text-primary">Personal workspace</p><div className="mt-4 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Good ideas deserve<br className="hidden sm:block"/> a place to land.</h1><p className="mt-3 max-w-lg text-sm leading-6 text-muted-foreground">Keep your active thinking light. Archived notes stay safely searchable whenever you need them.</p></div><QuickCapture projects={data.projects} defaultExpirationDays={data.settings.defaultExpirationDays}/></div><div className="mt-8 grid max-w-md grid-cols-2 gap-3"><Metric icon={<FolderKanban className="size-4"/>} label="Active projects" value={String(data.projects.length)}/><Metric icon={<Archive className="size-4"/>} label={archived ? "Archived notes" : "Visible notes"} value={String(data.notes.length)}/></div></header><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex rounded-xl border border-border bg-card p-1 text-sm"><Link href="/panel" className={`rounded-lg px-3 py-1.5 ${!archived ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"}`}>Active</Link><Link href="/panel?archived=1" className={`rounded-lg px-3 py-1.5 ${archived ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"}`}>Archive</Link></div><form className="flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-1"><Search className="size-4 text-muted-foreground"/><input name="q" defaultValue={params.q} className="w-full bg-transparent py-2 text-sm outline-none placeholder:text-muted-foreground" placeholder="Search your notes"/><input type="hidden" name="archived" value={archived ? "1" : ""}/></form></section><NotesList notes={data.notes} archived={archived}/></div>; }
function Metric({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-black/10 p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground">{icon}{label}</div><p className="mt-2 text-xl font-semibold">{value}</p></div>; }
