"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import { Command, X } from "lucide-react";
import { createNote } from "../actions";
import { toast } from "@/lib/toast";
type Project = { id: string; name: string };

export function QuickCapture({ projects, defaultProjectId, defaultExpirationDays }: { projects: Project[]; defaultProjectId?: string | null; defaultExpirationDays: number | null }) {
  const [open, setOpen] = useState(false); const [content, setContent] = useState(""); const [projectId, setProjectId] = useState(defaultProjectId ?? ""); const [days, setDays] = useState(String(defaultExpirationDays ?? "")); const [pending, start] = useTransition(); const area = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.code === "Space") { event.preventDefault(); setOpen(true); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  useEffect(() => { if (open) requestAnimationFrame(() => area.current?.focus()); }, [open]);
  const save = () => { if (!content.trim()) return; start(async () => { try { await createNote({ content, projectId: projectId || null, expirationDays: days ? Number(days) : null }); setContent(""); setOpen(false); toast.success("Thought captured."); } catch (error) { toast.fromError(error); } }); };
  if (!open) return <button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground transition hover:bg-primary-hover"><Command className="size-4"/>Add card<span className="hidden rounded border border-primary-foreground/25 px-1.5 py-0.5 font-mono text-[10px] sm:inline">⌃⇧ Space</span></button>;
  return <div className="fixed inset-0 z-50 flex items-start justify-center bg-black/70 p-4 pt-[10vh] backdrop-blur-sm" onMouseDown={() => !pending && setOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="quick-note-title" className="w-full max-w-2xl overflow-hidden rounded-lg border border-border bg-card shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><header className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-primary">New card</p><h2 id="quick-note-title" className="mt-1 text-base font-semibold">What needs to be remembered?</h2></div><button aria-label="Close quick capture" onClick={() => setOpen(false)} className="grid size-8 place-items-center rounded text-muted-foreground hover:bg-muted hover:text-foreground"><X className="size-4"/></button></header><div className="p-5"><textarea ref={area} value={content} onChange={(event) => setContent(event.target.value)} onKeyDown={(event) => { if (event.key === "Escape") setOpen(false); if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) { event.preventDefault(); save(); } }} className="min-h-40 w-full resize-none bg-transparent text-lg leading-7 text-foreground outline-none placeholder:text-muted-foreground" placeholder="A useful detail, a next step, a sudden idea…" aria-label="Note content"/><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-4"><div className="flex gap-2"><Select label="Lane" value={projectId} onChange={setProjectId}><option value="">Inbox</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</Select><Select label="Expires" value={days} onChange={setDays}><option value="">Never</option>{[1,3,7,14,30].map((day) => <option key={day} value={day}>{day} days</option>)}</Select></div><button onClick={save} disabled={pending || !content.trim()} className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-40">{pending ? "Saving…" : "Add card"}</button></div><p className="mt-4 text-xs text-muted-foreground">Ctrl/Cmd + Enter to save · Escape to close</p></div></section></div>;
}
function Select({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label className="rounded bg-muted px-2.5 py-1.5 text-xs text-muted-foreground">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="ml-1 bg-transparent text-foreground outline-none">{children}</select></label>; }
